services:
  db:
    image: postgres:15.5
    container_name: local-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - local-network

  migrate:
    build:
      context: .
      dockerfile: PurchaseAPI/Dockerfile.migrate
    container_name: purchase-migrate
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - local-network
    restart: "no"

  purchaseapi:
    build:
      context: .
      dockerfile: PurchaseAPI/Dockerfile
    container_name: purchaseapi
    ports:
      - "5001:80"
    depends_on:
      - migrate
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - local-network

volumes:
  postgresdata:

networks:
  local-network:
    driver: bridge
