services:
  db:
    image: postgres:15.5
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DevLocalPass123
      POSTGRES_DB: PurchaseDb
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - local-network

volumes:
  postgresdata:

networks:
  local-network:
    driver: bridge
