version: '3.8'

services:
  db:
    image: postgres:16
    container_name: local-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - local-network

volumes:
  postgresdata:

networks:
  local-network:
    driver: bridge
